### ISSUE TITLE
Failing to Auth when we deploy it on Vercel

### ISSUE THREAD

**Issue by hackerdud3** [SFSU-MyCareerCoach/resume-gen-frontend#11]
It may be due to the direct connection between the application and the database.

**Comment by Gravemind1142** [comment]
@shubhe25p @hackerdud3 Did you use vercel integrations to add supabase to the vercel project? I am not 100% sure if this is the solution, but it might be worth trying.

I can redeploy on a different vercel project on my account if needed.

See 
- https://vercel.com/integrations/supabase
- https://supabase.com/partners/integrations/vercel

**Comment by Gravemind1142** [comment]
Redeployed successfully with the following changes:
- Used the supabase-vercel integration
- Different repo
Used the same:
- Codebase
- Supabase Project and credentials

https://supabase-test-36q7vpv3l-gravemind1142.vercel.app/

I think there is a problem with the environment variables on the Vercel deployment, or the supabase-vercel integration has not been set up.

**Comment by shubhe25p** [comment]
Yep it works now, issue with env vars and redirect urls
