### ISSUE TITLE
[STepper] Hint text for Degree and Start date and end date 

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#14]
- Degree hint text needed such as BSc?  
- Start date hint text needed such as 09/01/2018.  Same as End date

**Comment by hjsonghjsong** [comment]
Also need a hint text for "Field of Stdy" like "Field of Study (e.g., Computer Science)".

**Comment by shubhe25p** [comment]
fixed in pr
