### ISSUE TITLE
[front-end] consistent button shape needed

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#18]
Through front-end, the button look should be consistent. It is one of essential things to make a professional UI. 

Please make a one button look across all front-end which includes 
- "LOGIN"
- "Back"
- "next"
- "Add Social link", 
- "Add POint"
- Add work Descorption
- ...

**Comment by shubhe25p** [comment]
fixed in pr
