### ISSUE TITLE
[stepper->skills] FINISH button not consistent with others.

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#24]
Suggest to change FINISH into others (like BACK button). 
![skills2](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/7aefa15e-6e78-4a40-8311-3aed49f2cb96)

**Comment by shubhe25p** [comment]
fixed with pr
