### ISSUE TITLE
[stepper] work description - removal of empty bullet

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#27]
1. Could we remove empty bullet in the edit box?  (Refer to ResumeNerd or others. If you select the suggestion, it goes to the 1st bullet.)
![emptybullet](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/c1ea9b13-a6c4-40f9-a015-6c97993bcb95)

**Comment by Gravemind1142** [comment]
Resolved df226d8d7ecca852012cd89a4711c722d98520a7
