### ISSUE TITLE
Job Perference : Text box could be larger with a long text input?

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#28]
How to produce
 1)  Go to https://www.indeed.com/jobs?q=software+engieer&l=Sunnyvale%2C+CA&vjk=357f9007d249694c. Select "Full Stack Engineer"  and Copy the text as the attached image.  (as image2)

 2) Paste it into Job preference.  (as image 1)

What is expected : 
 Text box gets larger when a large input is taken. 

Result : 
  No change in the text box 

![textbox](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/993e7063-5f68-4c37-aeef-2312265b2de8)
![JD](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/464f97d5-e7bd-4dd3-b857-22455ff29993)

**Comment by shubhe25p** [comment]
fixed in next pr
