### ISSUE TITLE
[Stepper] Project History (should remove the company name)

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#32]
Project History is for Project not involved for company. So company Name should not be there. 

It should have 
- Project Title, 
- Start Date  ( If you have a hint text. that would be great!  You can just say date/month/year. Do not have to say format: date/month/year, in the hint text. 
- End Data (Same).

**Comment by shubhe25p** [comment]
should be fixed in next pr
