### ISSUE TITLE
stepper : work experience & project : no way to add 2nd work exp

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#34]
There is no way to add 2nd work experience. 

After the "work deseciption", no button to add another work exp. 
![no2ndWorkEpx](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/5eba0b84-de50-4b39-b545-a29b6d402387)

**Comment by shubhe25p** [comment]
fixed in next pr
